remote_theme: nrandecker/particle
# Site settings
description: Mods meet games.

# User settings
username: M0D3RZ Games
user_description: Indie Game Studio
user_title: Indie Game Studio
email: brennan.osborne@lcabulldogs.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
